// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bchbhdhytfuwhpzuwlbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjaGJoZGh5dGZ1d2hwenV3bGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTg2NTUsImV4cCI6MjA2MjM3NDY1NX0.HL0_UInRVSH7Tx28-ahb0N5q2EomvEEQpu6oWTCvvi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);